config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  delete '/products', to: 'products#destroy_all'
  patch '/products', to: 'products#check_all'

  resources :allergens
  delete '/allergens', to: 'allergens#destroy_all'

  resources :menus, only: [:index, :create]
  
  get '/reactions', to: 'reactions#index'

  resources :profiles, only: [:show, :edit]
  
  #CRUD is not applicable so resource is not an appropriate choice,
  #instead manually build routes 
  #/search is the route, it points to (=>) searches#search (controller_name#action  where action is a function) 
  get '/search' => 'searches#search', as: 'search_search'
  #root 'allergens#index'
  root 'products#index'

  #When we use resources routes, we are mapping the browser 
  #requests (HTTP verbs and URLs) to the controller actions 
  #of our app

  # routes are mapped to: controller actions (Order of declaration matters)
=begin
  # get '/products', to: 'products#index', as: 'products_path'
  # get '/products/:id', to: 'products#show', as: 'post_path(object)'
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product_path(object)'
  # get '/products/new', to: 'products#new', as: 'new_product_path'
  # post '/products', to: 'products#create'
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  # resource routing maps routes to controller actions replacing code above
  # with a single line of code:   "resources :products"
=end

end

app/models/allergen.rb
class Allergen < ApplicationRecord
  #The model should be able to answer the question "Can user x do y to this object?"
  #When you write regular methods in the model those methods are all instance methods.  
  #In other words def some_method will be a method available on each retrieved record

  # dependent: :destroy, rails will destroy all reactions associated with Allergen when its deleted
  has_many  :reactions, dependent: :destroy
  # A has_many :through association is often used to set up a many-to-many connection 
  # with another model (Reaction). This association indicates that the declaring model (Allergen) can be 
  # matched with zero or more instances of another model (Product) by proceeding through a third model (Reaction).
  has_many  :products, through: :reactions
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'

  validates :category, presence: true
  #to validate more than one column (or more), you can add that to the scope
  validates_uniqueness_of :category, presence: true, :case_sensitive => false, :scope => [:user_id], length: {minimum: 3}
  validates :substances, presence: true, length: {minimum: 3}
  #validates :ingredients, format: { with: /;/, :message => "substances must be seperate by a ';'" }
  #validates :substances, format: { with: /;+/, :message => "must end with or be seperated by a ';'" }
  #Match any characters as few as possible until a ";" is found, without counting the ";".
  validates :substances, format: { with: /.+?(?=;)/, :message => "must end with or be seperated by a ';'" }

  def get_substances
    return self.substances.split(';')
  end

  # After allergen has been created or updated (and saved) check all products for
  # this allergen
  after_save do |allergen|
    if Product.any?
      Product.find_each {|product| product.check_for_allergens}
    end
  end 

end

app/controllers/allergens_controller.rb
class AllergensController < ApplicationController
  # Use before_action to set up an instance variable for an action, 
  # in this case, call set_allergen before calling edit or destroy
  before_action :set_allergen, only: [:edit, :destroy, :update, :show]
  before_action :authenticate_user!, only: [:index]

# run 'rails routes' then add '_path' to the Prefix to get the url

#       Prefix Verb   URI Pattern                   Controller#Action
#---------------------------------------------------------------------
#    allergens GET    /allergens(.:format)          allergens#index
#              POST   /allergens(.:format)          allergens#create
# new_allergen GET    /allergens/new(.:format)      allergens#new
#edit_allergen GET    /allergens/:id/edit(.:format) allergens#edit
#     allergen GET    /allergens/:id(.:format)      allergens#show
#              PATCH  /allergens/:id(.:format)      allergens#update
#              PUT    /allergens/:id(.:format)      allergens#update
#              DELETE /allergens/:id(.:format)      allergens#destroy
#         root GET    /                             allergens#index

# The purpose of the controller is to manage the incoming request and session

# GET '/'
  def index
    # Allergens.all accesses model layer and stores result in an instance variable
    # which is passed to the view
    @allergens = Allergen.where("user_id = ?", current_user)
    # render 'allergens/index' happens by default at end of method
  end

  # GET '/allergens/new'
  def new
    # set up a new instance variable which is an active record object
    # and pass it to the 'new' template in "new.html.erb" 
    @allergen = Allergen.new
    # render 'allergens/new' happens by default at end of method
  end

  # GET '/allergens/:id/edit'
  def edit # url will be something like /allergens/"Formaldehyde"/edit, edit form will be rendered
    # @allergen = Allergen.find_by category: params[:id]... this is now done by set_allergen
    # render 'allergens/edit by default
  end

  # POST '/allergens'
  # the general pattern used in the action create that handles
  # submission of model-backed forms 
  def create 
    # the form displayed in "new.html.erb" is submitted to action='/allergens' 
    # using verb method="post" which is routed to allergens#create.
    # @allergen, is populated with values (params) submitted from the form
    @allergen = Allergen.new(allergen_params)
    @allergen.creator = current_user

    if @allergen.save #returns "false" if it can't save
      flash[:success] = "Allergen was successfully created. Products re-checked for new Allergen."
      # redirect must be a url, can't render a view template
      # (add '_path' to the prefix to get the url)
      redirect_to allergen_path(@allergen) # index
    else
      # validation error occured. We must render to have access to 
      # "allergens.error.full_messages" array to display generated errors 
      render 'new'
    end
  end

  # PATCH '/allergens/:id'
  #the general pattern used in the action create that handles
  #submission of model-backed forms 
  def update # this is where the form displayed in 'edit' is submitted using verb "patch"
    # we have @allergen because set_allergen was invoked by before_action
    if @allergen.update(allergen_params)
      flash[:success] = "Allergen was successfully updated. Products re-checked to reflect update."
      redirect_to allergen_path(@allergen)
    else
      render 'edit'
    end
  end

  # GET '/allergens/:id'
  def show
    #already have @allergen at this point because 'set_allergen' was invoked by before_action
    #render 'allergens/show' (show.html.erb) automatically called before exiting this method
  end

  # DELETE '/allergens/:id'
  def destroy
    # already have @allergen at this point because 'set_allergen' was invoked
    @allergen.destroy
    flash[:success] = "Allergen was successfully deleted"
    redirect_to allergens_path # show.html.erb
  end

  def destroy_all
    # already have @allergen at this point because 'set_allergen' was invoked
    Allergen.destroy_all
    flash[:success] = "Allergens successfully deleted"
    redirect_to allergens_path # allergens/index
  end

  private

  def set_allergen
    # ask ActiveRecord to find the Allergen object in the db using 
    # either :category or :id from params and current user. Must check if string params[:id]
    # contains an integer ie: "12" or category ie: "Disperse Orange"
    !!params[:id].match(/^(\d)+$/) ?
      (@allergen = Allergen.find_by id: params[:id], user_id: current_user.id) :
      (@allergen = Allergen.find_by category: params[:id], user_id: current_user.id)
  end

  def allergen_params
    # use strong parameters to expose the fields we're interested in
    # require top level key be allergen and allow changes to category, substances
    params.require(:allergen).permit(:category, :substances)
    # To permit all attributes params.require(:post).permit!
  end

end

app/views/allergens/_allergen_details.html.erb
<!-- When a partial is called with a pluralized collection, then the individual instances of the partial have access to the member of the collection being rendered via a variable named after the partial -->
<% substances = allergen_details.get_substances %>
  <div class="col-md-3">
    <!-- Panel displaying allergen and substances -->

    <div class="panel">
      <div class="panel-heading">
        <div class="btn-group">
          <button type="button" class="btn btn-my-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= allergen_details.category %>  <span class="glyphicon glyphicon-menu-down"></span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit   ", edit_allergen_path(allergen_details.category)%></li>
            <li><%= link_to "Show   ", allergen_path(allergen_details.category)%></li>
            <li><%= link_to "Delete   ", allergen_path(allergen_details.category), method: :delete, data: { confirm: "Are you sure you want to delete this Allergen?"}%></li>
          </ul>
        </div>
      </div>
      <div class="panel-body">
        <% substances.each do |substance| %>
          <div class="substances text-color-not-ok">
            <%= substance %>
          </div>
        <% end %>
      </div>
    </div>

  <!-- end Panel display -->
  </div>

app/views/allergens/_form.html.erb
<!-- 
Forms are how we communicate with the db.
Model backed form helpers are tied to an object. There has to be a setter method, a virtual attribute or a column in the database, available for that object when using the model backed form helpers. We use model backed form helpers usually when we need to create, edit, or update an object.

By convention, form_for creates a form based on a specific model object. We are able to create, edit, and update that object's attributes. A form can be created by passing form_for a string or symbol relating to the object we want to deal with.

Here, the model-backed form takes an object @allergen and infers the action and all else based on convention. Form_for checks to see if @allergen is a new or existing object. If its a new object, it routes the information submitted to the 'create route' by setting action='/allergens' (uri) and method='post' (verb). This can be seen by using "inspect element" in chrome. In the case that #allergen is an exsisting object, its is routed to the update route, setting action='/allergens/id' and method='post' (this works because there is a hidden _method="patch" which converts post to patch for rails to use). The information submitted is stored in a params hash that can be used for mass assignment, in this case "allergen"=>{"category"=>"some category"}.
Allergen.create(params[:post]) is equivalent to Allergen.create("category"=>"some category")

text_field can to be any attribute (column) or virtual attribute of the allergen model that is permitted (in allergens_controller.rb under function 'allergen_params' is where we set permissions). In the allergen model, attributes are: id, category, substances
-->
<%= render 'shared/errors', obj: @allergen %>
 
<div class='row'>
  <!-- there are 12 cols in row, if boxes take up 8 'col-lg-8', then offset by 2 'col-lg-offset-2' on each side will center boxes -->
  <div class='form-horizontal col-lg-6 col-lg-offset-3'>
    <%= form_for @allergen do |f| %>
      <div class="form-group input-group-lg" >
        <%= f.label :category, :class => "label-style text-color-not-ok"%>
        <%= f.text_field :category, class: "form-control", placeholder: "Name of Allergen", autofocus: true %>
      </div>
      <br>
      <div class="form-group input-group-lg">
        <%= f.label :substances, :class => "label-style text-color-not-ok"%>
        <%= f.text_area :substances, rows: 10, class: "form-control", placeholder: "first substance; second substance; ... " %>
      </div>

      <button type="submit" class="btn btn-my-primary btn-xlarge">Save</button>
    <% end %>
    <br>
    <%= link_to "Cancel request and return to allergens listing", allergens_path %> 
  </div>
</div>

app/views/allergens/edit.html.erb
<h1 class="center-heading label-color">Edit Allergen</h1>

<%= render 'form' %>

app/views/allergens/index.html.erb
<body>
  <h1 class="center-heading label-color"><strong>Allergens</strong></h1>
  <%= render partial: "allergen_details", collection: @allergens %>
  <br>
  <div class="center">
    <%= link_to "Add New Allergen", new_allergen_path, class: "btn btn-xlarge btn-my-primary" %>
  </div>
  <br>
</body>

app/views/allergens/new.html.erb
<h1 class="center-heading text-color-not-ok">Add a New Allergen</h1>

<%= render 'form' %>

app/views/allergens/show.html.erb
<%= render partial: "shared/allergen_target", collection: [@allergen] %>