config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  delete '/products', to: 'products#destroy_all'
  patch '/products', to: 'products#check_all'

  resources :allergens
  delete '/allergens', to: 'allergens#destroy_all'

  resources :menus, only: [:index, :create]
  
  get '/reactions', to: 'reactions#index'

  resources :profiles, only: [:show, :edit]
  
  #CRUD is not applicable so resource is not an appropriate choice,
  #instead manually build routes 
  #/search is the route, it points to (=>) searches#search (controller_name#action  where action is a function) 
  get '/search' => 'searches#search', as: 'search_search'
  #root 'allergens#index'
  root 'products#index'

  #When we use resources routes, we are mapping the browser 
  #requests (HTTP verbs and URLs) to the controller actions 
  #of our app

  # routes are mapped to: controller actions (Order of declaration matters)
=begin
  # get '/products', to: 'products#index', as: 'products_path'
  # get '/products/:id', to: 'products#show', as: 'post_path(object)'
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product_path(object)'
  # get '/products/new', to: 'products#new', as: 'new_product_path'
  # post '/products', to: 'products#create'
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  # resource routing maps routes to controller actions replacing code above
  # with a single line of code:   "resources :products"
=end

end

app/views/shared/_allergen_target.html.erb
<!-- When a partial is called with a pluralized collection, then the individual instances of the partial have access to the member of the collection being rendered via a variable named after the partial -->
<% substances = allergen_target.get_substances %>
<div class="panel-small">
  <div class="panel-heading-small">
    <div class="btn-group">
      <button type="button" class="btn btn-lg btn-my-primary btn-disabled" >
        <%= allergen_target.category %>
      </button>
    </div>
  </div>
  <div class="panel-body-small">
    <% substances.each do |substance| %>
      <% if substance.upcase.include?(search_item.upcase)%> 
        <div class="substances text-color-not-ok">
          <%= highlight(substance, search_item) %> 
        </div> 
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_errors.html.erb
<!-- Rails validations are triggered when the data submissions try to hit the database.The errors are saved on the model object. When there are validation errors, they are saved to the object.errors. We display the validation messages by referencing the object.errors.full_messages method like below. By using the full_messages method, the errors are displayed in a nice, readable sentence format. -->
<!-- Here, obj must be an active record object. -->

<% if obj.errors.any? %>
  <div class="row">
    <!-- <div class="col-xs-8 col-xs-offset-2"> -->
      <div class="col-lg-6 col-lg-offset-3">
      <div class="alert-error">
        <h2 class="center">
          <%= pluralize(obj.errors.count, "error") %> prohibited this product from being saved:
        </h2>
        <ol class="center">
          <% obj.errors.full_messages.each do |msg| %>
            <div>
            <li>
              <%= msg %>
            </li>
          </div>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_product.html.erb
<!-- if invoked from search.html.erb, then there will be a search_item passed in -->
<% product_reactions = product.causes_reaction %>

<% if product_reactions.any? %>
  <% search_item = product_reactions.select(:reactive_ingredient).distinct.pluck(:reactive_ingredient) %> 
<% end %>


<tr class="product-index">
  <td class="<%= product_reactions.empty? ? 'text-color-ok' : 'text-color-not-ok' %>">
    <%= highlight(product.name, search_item) %>
  </td>
  <td class="<%= product_reactions.empty? ? 'text-color-ok' : 'text-color-not-ok' %>">
    <%= highlight(product.ingredients, search_item) %>
  </td>
  <% if index_view %>     
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Show', product_path(product) %></td>
    <td><%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: "Are you sure?"} %></td>
  <% end %>
</tr>
  

app/views/shared/_reactive_product.html.erb
<% reactions_to_product = get_all_product_reactions(reactive_product) %>
<tr class="text-color-not-ok">
  <td>
    <%= Product.find(reactive_product).name %>
  </td>
  <td>
    <%= highlight(get_reactive_ingredients(reactions_to_product), search_item) %>
  </td>
  <td>
    <%= highlight(get_allergen_categories(reactions_to_product), search_item) %>
  </td>
  <td>
    <%= highlight(get_reactive_substances(reactions_to_product), search_item) %>
  </td>